#!/usr/bin/env bash

cd "$DOSROOT"

if fzf_can_show_image; then
	game="$(cat index.txt | fzf --preview='fzf_preview -i boxart/{}.jpg')"
else
	game="$(cat index.txt | fzf --preview='fzf_preview boxart/{}.jpg')"
fi
if [[ "$game" != "" ]]; then
    flatpak run io.github.dosbox-staging -conf ./common.conf -conf "./dosbox/$game.conf"

    # And this is MRU.
    # https://stackoverflow.com/a/67031431
    printf "/%s/m0\nwq\n" "$game" | ed -s index.txt -
fi