#!/usr/bin/env bash

index="$(realpath "$1")"

if [ ! -f "$index" ]; then
	echo Index not found.
	exit 1
fi

cd "$(dirname "$1")" || exit 1

if fzf_can_show_image; then
	flick="$(cat "$index" | fzf -d"$(printf '\t')" --accept-nth=1 --with-nth=2 --preview='fzf_preview -i {1}')"
else
	flick="$(cat "$index" | fzf -d"$(printf '\t')" --accept-nth=1 --with-nth=2 --preview='fzf_preview {1}')"
fi

if [ -f "$flick" ]; then
	mpv "$flick"
fi
