#!/usr/bin/env bash

index="$(realpath "$1")"

if [ ! -f "$index" ]; then
	echo Index not found.
	exit 1
fi

cd "$(dirname "$1")" || exit 1

flick="$(cat "$index" | fzf -d"$(printf '\t')" --accept-nth=1 --with-nth=2 --preview='fzf_preview {1}')"

if [ -f "$flick" ]; then
	mpv "$flick"
fi
